global:
 scrape_interval: 10s
 evaluation_interval: 10s
 external_labels:
   monitor: 'Monitoring'

scrape_configs:

 - job_name: 'kafka'
   static_configs:
     - targets: [ 'kafka1:7071' ]
     - targets: [ 'kafka2:7072' ]
     - targets: [ 'kafka3:7073' ]
#      - targets: [ 'kafka4:7074' ]
#      - targets: [ 'kafka5:7075' ]
#      - targets: [ 'kafka6:7076' ]
 - job_name: 'prometheus'
   static_configs:
    - targets: [ 'host.docker.internal:9090' ]
 - job_name: 'node-exporter'
   static_configs:
     - targets: [ 'node-exporter:9100' ]
 - job_name: 'cAdvisor'
   static_configs:
     - targets: [ 'cadvisor:8080' ]